### PR TITLE
Update kgbase client to resolve feedback

### PR DESCRIPTION
**Pull request by raphaelseo**
### NOTE
https://github.com/thinknum/kgbase/pull/148 needs to be merged before.

Address https://github.com/thinknum/kgbase/issues/118
Address https://github.com/thinknum/kgbase/issues/133

### CODE REVIEW

**Comment by apairmont** [comment]
Sounds like we need more tests if we want to keep from breaking stuff...

**Comment by vojto** [comment]
Well, adding tests for the client wouldn't resolve this problem. If you change the API, you have to update the example script.

The example script is kinda like an integration test. You run it to make sure you can still accomplish the same things as before.

When it comes to client code, adding real integration testing would be very complicated, and adding unit tests wouldn't be very useful.

So having an example script is a good middle ground to make sure you didn't break anything.

**Comment by apairmont** [comment]
I meant tests for the example. Not always possible of course.

**Comment by vojto** [comment]
Still complicated...

It would involve spinning up a KgBase server, making sure requests were executed, and maybe checking database if everything was updated correctly...

**Comment by apairmont** [comment]
Understood. For datalab we use a lot of “mocking” to test a lot of the components. It allows us to catch 90% of breaking API changes. But that remaining 10% would require much of what you mention as well.

**Comment by raphaelseo** [comment]
@vojto I created test script here. https://github.com/thinknum/kgbase-client/pull/31/files#diff-54d77fc8d15a74f50f303fd3b7417893

I think that's because I renamed function. If you let me know your script is, then I will check it out.

**Pull request merged**
